docklet_bluetooth_speaker_sources = [
  'BluetoothSpeakerDocklet.vala',
  'BluetoothSpeakerDockItem.vala',
  'BluetoothSpeakerPreferences.vala',
]

shared_module(
  'docklet-bluetooth-speaker',
  docklet_bluetooth_speaker_sources,
  dependencies: [plank_dep, plank_base_dep],
  install: true,
  install_dir: docklets_dir,
)
